### ISSUE TITLE
Error with minify after upgrade from 8.0.10 to 8.0.11

### ISSUE THREAD

**Issue by izu23** [hotwired/turbo#1330]
After i upgraded from version 8.0.10 to 8.0.11 i got the following issue:

Uncaught TypeError: ya is not a function

at this positon:

function bi(t, n) {
return ya(t, n) && !nt.drive.unvisitableExtensions.has(_a(t))
}

im using this build
"build": "esbuild app/javascript/application.js --bundle --minify --sourcemap --format=esm --outdir=app/assets/builds --public-path=/assets --tree-shaking=false"

these are my dependencies

"dependencies": {
"@hotwired/turbo": "8.0.10",
"@hotwired/turbo-rails": "8.0.10",
"blueimp-file-upload": "^10.32.0",
"esbuild": "^0.21.5",
"jquery": "^3.7.1",
"sass": "^1.80.4"
},
"resolutions": {
"@hotwired/turbo": "8.0.10"
}

and im using node 22.8.0

this is my application.js

import './src/init_jquery';
import './vendor/jquery-ui';
import "@hotwired/turbo-rails"

and this the init_jquery.js

import jquery from 'jquery';
window.$ = jquery;
window.jQuery = jquery;
$ = jquery;
